version: "3.1"
services:
    mongo:
        image: mongo:4.2
        container_name: mongo
        restart: always
        ports: 
            - ${MONGO_PORT}:27017
        environment: 
            MONGO_INITDB_DATABASE: ${MONGO_NAME}  

    redis:
        image: redis
        container_name: redis
        restart: always
        expose:
            - ${REDIS_PORT}

    api:
        image: node:latest 
        container_name: api
        restart: always
        env_file: 
            - .env 
        depends_on: 
            - mongo
            - redis
        ports: 
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes: 
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: npm run start:prod
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "5"